//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: message/station.proto
namespace message.station
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"node_property")]
  public partial class node_property : global::ProtoBuf.IExtensible
  {
    public node_property() {}
    
    private uint _id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _type = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint type
    {
      get { return _type; }
      set { _type = value; }
    }
    private uint _state = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint state
    {
      get { return _state; }
      set { _state = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _neighbourCollect = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(5, Name=@"neighbourCollect", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> neighbourCollect
    {
      get { return _neighbourCollect; }
    }
  
    private uint _operateType = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"operateType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint operateType
    {
      get { return _operateType; }
      set { _operateType = value; }
    }
    private uint _overTimeType = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"overTimeType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint overTimeType
    {
      get { return _overTimeType; }
      set { _overTimeType = value; }
    }
    private uint _removalType = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"removalType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint removalType
    {
      get { return _removalType; }
      set { _removalType = value; }
    }
    private uint _insulateType = default(uint);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"insulateType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint insulateType
    {
      get { return _insulateType; }
      set { _insulateType = value; }
    }
    private uint _faultState = default(uint);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"faultState", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint faultState
    {
      get { return _faultState; }
      set { _faultState = value; }
    }
    private bool _isFaultEdgeConnected;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"isFaultEdgeConnected", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool isFaultEdgeConnected
    {
      get { return _isFaultEdgeConnected; }
      set { _isFaultEdgeConnected = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _indexArea = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(13, Name=@"indexArea", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> indexArea
    {
      get { return _indexArea; }
    }
  
    private readonly global::System.Collections.Generic.List<bool> _isExitArea = new global::System.Collections.Generic.List<bool>();
    [global::ProtoBuf.ProtoMember(14, Name=@"isExitArea", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<bool> isExitArea
    {
      get { return _isExitArea; }
    }
  
    private readonly global::System.Collections.Generic.List<bool> _isGather = new global::System.Collections.Generic.List<bool>();
    [global::ProtoBuf.ProtoMember(15, Name=@"isGather", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<bool> isGather
    {
      get { return _isGather; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"connect_switch")]
  public partial class connect_switch : global::ProtoBuf.IExtensible
  {
    public connect_switch() {}
    
    private uint _transferCode = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"transferCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint transferCode
    {
      get { return _transferCode; }
      set { _transferCode = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _path1 = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(2, Name=@"path1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> path1
    {
      get { return _path1; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _path2 = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(3, Name=@"path2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> path2
    {
      get { return _path2; }
    }
  
    private uint _count = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint count
    {
      get { return _count; }
      set { _count = value; }
    }
    private bool _isConnect;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"isConnect", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool isConnect
    {
      get { return _isConnect; }
      set { _isConnect = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"connect_path")]
  public partial class connect_path : global::ProtoBuf.IExtensible
  {
    public connect_path() {}
    
    private uint _id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _remainderCapacity = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"remainderCapacity", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint remainderCapacity
    {
      get { return _remainderCapacity; }
      set { _remainderCapacity = value; }
    }
    private bool _isUpdated;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"isUpdated", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool isUpdated
    {
      get { return _isUpdated; }
      set { _isUpdated = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"distribution_power_area")]
  public partial class distribution_power_area : global::ProtoBuf.IExtensible
  {
    public distribution_power_area() {}
    
    private readonly global::System.Collections.Generic.List<uint> _areaSwitch = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(1, Name=@"areaSwitch", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> areaSwitch
    {
      get { return _areaSwitch; }
    }
  
    private uint _upadetedFlag = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"upadetedFlag", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint upadetedFlag
    {
      get { return _upadetedFlag; }
      set { _upadetedFlag = value; }
    }
    private bool _isUpadeted;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"isUpadeted", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool isUpadeted
    {
      get { return _isUpadeted; }
      set { _isUpadeted = value; }
    }
    private bool _isFaultArea;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"isFaultArea", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool isFaultArea
    {
      get { return _isFaultArea; }
      set { _isFaultArea = value; }
    }
    private bool _isExitFaultMessage;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"isExitFaultMessage", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool isExitFaultMessage
    {
      get { return _isExitFaultMessage; }
      set { _isExitFaultMessage = value; }
    }
    private uint _upadetedFull = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"upadetedFull", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint upadetedFull
    {
      get { return _upadetedFull; }
      set { _upadetedFull = value; }
    }
    private uint _removalType = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"removalType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint removalType
    {
      get { return _removalType; }
      set { _removalType = value; }
    }
    private uint _insulateType = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"insulateType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint insulateType
    {
      get { return _insulateType; }
      set { _insulateType = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"distribution_station")]
  public partial class distribution_station : global::ProtoBuf.IExtensible
  {
    public distribution_station() {}
    
    private uint _areaCount = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"areaCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint areaCount
    {
      get { return _areaCount; }
      set { _areaCount = value; }
    }
    private bool _isComplted;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"isComplted", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool isComplted
    {
      get { return _isComplted; }
      set { _isComplted = value; }
    }
    private bool _isGatherCompleted;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"isGatherCompleted", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool isGatherCompleted
    {
      get { return _isGatherCompleted; }
      set { _isGatherCompleted = value; }
    }
    private bool _isGatherCalculateCompleted;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"isGatherCalculateCompleted", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool isGatherCalculateCompleted
    {
      get { return _isGatherCalculateCompleted; }
      set { _isGatherCalculateCompleted = value; }
    }
    private uint _switchRef = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"switchRef", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint switchRef
    {
      get { return _switchRef; }
      set { _switchRef = value; }
    }
    private bool _isAlreayExitedFault;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"isAlreayExitedFault", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool isAlreayExitedFault
    {
      get { return _isAlreayExitedFault; }
      set { _isAlreayExitedFault = value; }
    }
    private bool _isExitedInsulateFailure;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"isExitedInsulateFailure", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool isExitedInsulateFailure
    {
      get { return _isExitedInsulateFailure; }
      set { _isExitedInsulateFailure = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"faultdeal_handle")]
  public partial class faultdeal_handle : global::ProtoBuf.IExtensible
  {
    public faultdeal_handle() {}
    
    private uint _switchPropertyID = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"switchPropertyID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint switchPropertyID
    {
      get { return _switchPropertyID; }
      set { _switchPropertyID = value; }
    }
    private uint _state = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint state
    {
      get { return _state; }
      set { _state = value; }
    }
    private uint _lastState = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"lastState", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint lastState
    {
      get { return _lastState; }
      set { _lastState = value; }
    }
    private uint _nextState = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"nextState", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint nextState
    {
      get { return _nextState; }
      set { _nextState = value; }
    }
    private bool _isRun;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"isRun", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool isRun
    {
      get { return _isRun; }
      set { _isRun = value; }
    }
    private uint _step = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"step", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint step
    {
      get { return _step; }
      set { _step = value; }
    }
    private uint _startTime = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"startTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint startTime
    {
      get { return _startTime; }
      set { _startTime = value; }
    }
    private uint _limitTime = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"limitTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint limitTime
    {
      get { return _limitTime; }
      set { _limitTime = value; }
    }
    private uint _t1 = default(uint);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"t1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint t1
    {
      get { return _t1; }
      set { _t1 = value; }
    }
    private uint _t2 = default(uint);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"t2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint t2
    {
      get { return _t2; }
      set { _t2 = value; }
    }
    private uint _t3 = default(uint);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"t3", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint t3
    {
      get { return _t3; }
      set { _t3 = value; }
    }
    private uint _t4 = default(uint);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"t4", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint t4
    {
      get { return _t4; }
      set { _t4 = value; }
    }
    private uint _t5 = default(uint);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"t5", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint t5
    {
      get { return _t5; }
      set { _t5 = value; }
    }
    private uint _checkOpenTime = default(uint);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"checkOpenTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint checkOpenTime
    {
      get { return _checkOpenTime; }
      set { _checkOpenTime = value; }
    }
    private uint _checkBackupTime = default(uint);
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"checkBackupTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint checkBackupTime
    {
      get { return _checkBackupTime; }
      set { _checkBackupTime = value; }
    }
    private uint _rejectTime = default(uint);
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"rejectTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint rejectTime
    {
      get { return _rejectTime; }
      set { _rejectTime = value; }
    }
    private uint _reciveRemovalSuccessTime = default(uint);
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"reciveRemovalSuccessTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint reciveRemovalSuccessTime
    {
      get { return _reciveRemovalSuccessTime; }
      set { _reciveRemovalSuccessTime = value; }
    }
    private uint _reciveConnectTime = default(uint);
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"reciveConnectTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint reciveConnectTime
    {
      get { return _reciveConnectTime; }
      set { _reciveConnectTime = value; }
    }
    private bool _isCheckPass;
    [global::ProtoBuf.ProtoMember(19, IsRequired = true, Name=@"isCheckPass", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool isCheckPass
    {
      get { return _isCheckPass; }
      set { _isCheckPass = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StationMessage")]
  public partial class StationMessage : global::ProtoBuf.IExtensible
  {
    public StationMessage() {}
    
    private readonly global::System.Collections.Generic.List<uint> _idCollect = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(1, Name=@"idCollect", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> idCollect
    {
      get { return _idCollect; }
    }
  
    private bool _isGainComplted;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"isGainComplted", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool isGainComplted
    {
      get { return _isGainComplted; }
      set { _isGainComplted = value; }
    }
    private node_property _node = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"node", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public node_property node
    {
      get { return _node; }
      set { _node = value; }
    }
    private connect_switch _connect = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"connect", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public connect_switch connect
    {
      get { return _connect; }
      set { _connect = value; }
    }
    private readonly global::System.Collections.Generic.List<connect_path> _con_path = new global::System.Collections.Generic.List<connect_path>();
    [global::ProtoBuf.ProtoMember(5, Name=@"con_path", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<connect_path> con_path
    {
      get { return _con_path; }
    }
  
    private readonly global::System.Collections.Generic.List<distribution_power_area> _power_area = new global::System.Collections.Generic.List<distribution_power_area>();
    [global::ProtoBuf.ProtoMember(6, Name=@"power_area", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<distribution_power_area> power_area
    {
      get { return _power_area; }
    }
  
    private distribution_station _distribution = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"distribution", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public distribution_station distribution
    {
      get { return _distribution; }
      set { _distribution = value; }
    }
    private faultdeal_handle _fault_handle = null;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"fault_handle", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public faultdeal_handle fault_handle
    {
      get { return _fault_handle; }
      set { _fault_handle = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}